### ISSUE TITLE
error: If mode is 'interp', window_length must be less than or equal to the size of x.

### ISSUE THREAD

**Issue by sjfleck** [AntoineHo/HapPy#7]
Thank you for developing this tool. I tried to use it on my genome assemblies before and after purge haplotigs. This is an example of my commands:

#generate BAM file (I already had this BAM file and repurposed it for HapPy):
minimap2 -t 4 -ax map-ont $GENOME $ONT > aln.sam 
samtools sort -m 1G -o aln.sorted.bam -T tmp.ali aln.sam 
samtools index aln.sorted.bam

#run HapPy:
happy coverage --threads=16 --outdir=$OUT $BAM
happy estimate --max-contaminant 35 --max-diploid 120 -S 871M -O happy_stats.txt -P $OUT/aln.sorted.bam.hist

After processing all the reference contigs, this is the error that comes up:

Traceback (most recent call last):
  File "/projects/academic/vaalbert/modulefiles/anaconda3/envs/happy-env/bin/happy", line 8, in <module>
    sys.exit(main())
  File "/projects/academic/vaalbert/modulefiles/anaconda3/envs/happy-env/lib/python3.10/site-packages/happy/Hap.py", line 50, in main
    command.execute()
  File "/projects/academic/vaalbert/modulefiles/anaconda3/envs/happy-env/lib/python3.10/site-packages/happy/commands.py", line 86, in execute
    happye.estimate_haploidy(
  File "/projects/academic/vaalbert/modulefiles/anaconda3/envs/happy-env/lib/python3.10/site-packages/happy/estimate.py", line 37, in estimate_haploidy
    smoothed = [s for s in savgol_filter(freqs, 41, 3) if s >= 0]
  File "/projects/academic/vaalbert/modulefiles/anaconda3/envs/happy-env/lib/python3.10/site-packages/scipy/signal/_savitzky_golay.py", line 339, in savgol_filter
    raise ValueError("If mode is 'interp', window_length must be less "
ValueError: If mode is 'interp', window_length must be less than or equal to the size of x.

I see that you example included the "--secondary=no" option for minimap2 and mine didn't. I will try that. Any additional insight into how I can fix this would be greatly appreciated. Thank you

**Comment by AntoineHo** [comment]
Hello,
Thank you for reporting this,

I think this is an error in the .hist file generated by `happy coverage`, either it is truncated or perhaps it is an unexpected behavior from hap.py.
Could you upload `$OUT/aln.sorted.bam.hist` so that I can have a look? My guess is that the histogram contains very high frequency peaks it can happen when some contigs have few to no reads aligned.

You can also try using `happy autoest --debug --plot <histogram_file>` it will probably fail as well but it will output some useful plots that you can also upload (it's optional).

Cheers,
Antoine

**Comment by sjfleck** [comment]
Thanks for the response. I'll attach the histogram file. I also tried to use the "happy autoest" command, but it only produces an error with the usage, so I'm not sure what's going wrong.

[aln.sorted.bam.hist.txt](https://github.com/AntoineHo/HapPy/files/8091117/aln.sorted.bam.hist.txt)

**Comment by sjfleck** [comment]
I should also mention that there shouldn't be anything too strange with the BAM file because it worked perfectly with purge_haplotigs. This is the coverage histogram from the first step of Purge_haplotigs

![F_a aln sorted bam histogram](https://user-images.githubusercontent.com/53409202/154544661-6f27a1bc-68a4-4c48-b916-d598721f50e4.png)

**Comment by sjfleck** [comment]
I remade the bam file using the "--secondary=no" option for minimap:

minimap2 -t 16 -ax map-ont --secondary=no $GENOME $ONT | samtools sort --threads 16 -o aln.sorted.bam -T tmp.ali
samtools index aln.sorted.bam
happy coverage --threads=16 --outdir=$OUT $BAM
happy estimate --max-contaminant 35 --max-diploid 120 -S $SIZE -O happy_stats.txt -P $OUT/aln.sorted.bam.hist

and it resulted in the same error message

**Comment by AntoineHo** [comment]
Hello,

I have pushed a major update of HapPy. It should work now, I have not tried it extensively but it should work now.

The specific problem with the histogram was that I did not anticipate it on lower than 40X coverage and it failed to smooth the curve because the smoothing window used by the function `savgol_filter(freqs, 41, 3)` was set by default on 41.

I have added an argument to change the window size `-w` but in your specific case, you can simply deactivate the smoothing using `--no-smooth`. By default it will now detect that the max coverage is lower than the window size and skip smoothing.

To use it:
```
git clone https://github.com/AntoineHo/HapPy.git

python path/to/Hap.py estimate aln.sorted.bam.hist.txt -s 871M -o aln_stats --plot
```

Here are the statistics and plots output:
```
AUC(Haploid): H = 641144862
AUC(Diploid): D = 248467765
Ratio: 1-(D/H) = 0.612
Haploidy: H/(H + (D/2)) = 0.838
```
![aln_stats plot](https://user-images.githubusercontent.com/28657792/154814578-482b59a4-3fd3-4984-82a1-6c6a6c04372e.png)

Since in this case, the automatic low limit was set to 8 I would advise to redo it using manual limits: 0 (no low coverage peak), 14 based on the plot above and 35 (maximum coverage in your distribution).
```
python path/to/Hap.py estimate aln.sorted.bam.hist.txt -s 871M -o aln_stats --plot --limit-low 0 --limit-dip 14 --limit-high 35
```

Which outputs now: seems a bit less haploid but the TSS is better (meaning your assembly is probably more complete)
```
AUC(Haploid): H = 641144862
AUC(Diploid): D = 409767110
Ratio: 1-(D/H) = 0.361
Haploidy: H/(H + (D/2)) = 0.758
```
![aln_stats plot2](https://user-images.githubusercontent.com/28657792/154814727-4cdc2b64-92d4-4578-abf1-12ff69ebcb9f.png)

Do not hesitate if you have more questions.

Cheers,
Antoine

**Comment by sjfleck** [comment]
Thank you for this update. It worked perfectly. I have one final question. I said that I wanted to test my Flye assemblies before and after using purge_haplotigs. Purge_haplotigs did a pretty good job with making the assemblies haploid, but I was hoping to see what HapPy thought of it. Since there is only a single peak after purge_haplotigs, I'm not sure what to choose for "--limit-dip". I tried leaving it out, since the default is auto, but I get this error:

You must set all values for thresholds -ll, -ld and -lh...

For example, here is the before and after for one of my samples. Before purge_haplotigs:
![happy Fraxinus_americana aln_stats plot](https://user-images.githubusercontent.com/53409202/155053280-d7a93d7a-62e5-44f5-bb0b-3af61e071d48.png)

After purge_haplotigs:
![happy Fraxinus_americana Purge_Haplotigs aln_stats plot](https://user-images.githubusercontent.com/53409202/155053325-2c14d23e-2c31-4faf-b690-3d6224a7fcb7.png)

Do you have any recommendations for setting the values for afterward? Thanks!

**Comment by AntoineHo** [comment]
Hello,

Looks like you have a haploid assembly, you can either try setting both -ll and -ld to 0 but it would give you a ratio of 1.0 and be not really informative. You could also try to set both -ll and -ld to 2 (or 4) so that it will not count the very low coverage regions. 

However, what I would probably check in this case, is the TSS (shown in the graph title). If you are confident of your expected genome size, it will give you a score of how "complete" the assembly is. Note that this score may be underestimated when there are large hemizygous regions (present on only one haplotype) for instance when there is a big difference in the size of sexual chromosomes. The TSS, compares the total haploid size in your assembly with the expected genome size (discarding low coverage bases) and it gives you a value between 0.0 and 1.0, the closer to 1.0 the more complete your assembly.

If after purging the TSS drops then the purging step probably discarded too many contigs (perhaps hemizygous regions). I would compare the TSS with setting -ll to 2 or 4 because these come from regions that appear to not be covered at all. They may be contaminants for instance.

Hope this helps,

Cheers,
Antoine

**Comment by sjfleck** [comment]
Thanks for the help and I have 2 final questions:
1. How is the haplotig ratio calculated? (it's at the top of the histogram with AUC and TSS)
2. What does the assembly completeness statistic, the TSS initialism, stand for?

In terms of your questions, I'm fairly confident in the genome size estimates. They were generated from another research group's publication using flow cytometry. I took their 1C measurements (92, 16, and 80 biological replicates) and averaged them for each of the species I'm looking at.

Species: Est. size -> Assembly size after Purge Haplotigs
Species A: 871M -> ~852M (within 1 STDEV)
Species B: 818M -> ~776M (between 1-2 STDEV)
Species C: 857M -> ~842M (within 1 STDEV)

I also think purge haplotigs worked relatively well. Afterward, I was pretty pleased with the assembly results:
Species A: ~8,700 fewer contigs & the number of complete BUSCOs increased
Species B: ~1400 fewer contigs & the total number of BUSCOs increased
Species C: ~7,100 fewer contigs & only 10 fewer BUSCOs overall

I'm rerunning the program now with your recommendations for the assembly after purge haplotigs. Hopefully they're not too over-purged, but the folks over at purge haplotigs mentioned that slight over-purging can be hard to avoid.

**Comment by AntoineHo** [comment]
Hello,

The haplotig ratio is computed as follow:
```
AUC is the Area Under Curve
AUC(Haploid_peak) = H
AUC(Diploid_peak) = D
AUC_ratio = 1 - (D/H)
```
The closer the ratio to 1.0 the more haploid the assembly (D=0). However, it is better to look at the Haploidy score that is normalised whereas the haplotig ratio can go to -infinity

The TSS stands for Total Size Score and is computed as follows:
```
G = estimated genome size
TSS = 1 - ( abs(G - (H + D/2)) / G ) 
```
When TSS is close to 1.0, it is likely that your assembly contains at least one representation of all the sequences in the genome. When it is below 1.0, then some sequences that should be present are likely not represented at all and when it is above 1.0, you may have a bigger genome than expected or contaminants.

**Comment by sjfleck** [comment]
Thank you very much! I was rerunning everything and found a small error. When I'm using the new version, this command doesn't work:
python $HAPPY/Hap.py coverage --threads=16 --outdir=$OUT $BAM

You can still run "python $HAPPY/Hap.py coverage -h", but getting it to run normally produces this error:
ERROR: Sambamba is not found!

But if I switch to the conda environment, this version of the command does work:
happy coverage --threads=16 --outdir=$OUT $BAM

I don't mind using the conda environment for coverage and the new update for estimate, but I just wanted to let you know I came across this issue. Thanks again.

**Comment by sjfleck** [comment]
I have a final update and question. When I run -ll 2 -ld 2, the TTS = 0.964 (-ll 4 -ld 4 TTs = 0.961). The stats are:
AUC(Haploid) = 840013237
AUC(Diploid) = 0
Ratio = 1.0
Haploidy = 1.0

![happy Fraxinus_americana Purge_Haplotigs aln_stats plot ll2_ld2 no_smooth](https://user-images.githubusercontent.com/53409202/158919880-604f09f8-2aa6-409c-aa8a-dc4cdcd5f313.png)

There is still a single peak with --no-smooth, it's a little bulged out on the lower coverage side. Would you recommend sticking with -ll 2 -ld 2 or does the bulge indicate diploidy remaining?

I should mention that I have a strong sense that there is some heterozygosity remaining based on a self-vs-self frequency plot for synonymous substitution rates (Ks) between syntenic CDS pairs. In this png, you can see some very low frequency CDS pairs that are very similar and very recent. I interpret this as different alleles between bits of uncollapsed chromosome pairs.

![master_63073_63073 CDS-CDS last tdd10 cs0 filtered dag all go_D20_g10_A5 aligncoords gcoords_ct0 w1000 spa1 ks sr cs1 csoS log nsd hist](https://user-images.githubusercontent.com/53409202/158920474-7fb011b5-84c8-4c8c-a4a9-b23039f6779d.png)

I will close this issue after hearing your thoughts and thank you for all your help with helping me utilize HapPy to the fullest extent.

**Comment by AntoineHo** [comment]
Hello, sorry I did not get notified when you reopened the issue so I see it only now.

It could very well be some uncollapsed haplotigs remaining. However, other things can explain why some bumps remain in the coverage histogram. Some regions in the assembly can actually be haploid, e.g.: sexual chromosomes or hemizygous deletions, they will be covered ~0.5x the average yet they should not be purged by tools like purge haplotigs or purge dups since there are no homologous regions to be found in alignments.

I think that I would check the coverage in the regions of the "suspected alleles" based on your Ks graph, if it is halved then it probably means that you still have some diploidy left although barely detectable. If the coverage is normal then they could be duplications or transposons for instance.

Hope this can help you.
Cheers
